# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.4
  - nightly
notifications:
  email: false
script:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
- julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("DictWrappers"); Pkg.test("DictWrappers"; coverage=true)'
after_success:
- julia -e 'cd(Pkg.dir("DictWrappers")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
